### ISSUE TITLE
CLI DX: kafka provider name does not match --provider option for stream create

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#101]
CLI users have to translate the `<name>` of the kafka provider into `<name>-kafka-provisioner` when they create a stream using that provider. The CLI help message provides no help in this regard.

```sh
riff streaming kafka-provider create franz --bootstrap-servers kafkabroker:9092

riff streaming stream create in  --provider franz-kafka-provisioner --content-type application/json 
```

**Comment by scothis** [comment]
This will be resolved by #102 and projectriff/system#145
