### ISSUE TITLE
riff ... delete --all should list the resources that are deleted

### ISSUE THREAD

**Issue by trisberg** [projectriff/cli#111]
The current behavior is to just display

```
$ riff function delete --all
Deleted functions in namespace "default"
```

It would be nicer to mimic kubectl and list the deleted resources

```
$ kubectl delete function --all
function.build.projectriff.io "upper" deleted
```

**Comment by scothis** [comment]
This will require listing the resources that match the selector and then deleting each item in that list individually. So it will be a lot slower and more error prone. It will also introduce the possibility of partial failure which we don't have today.
