### ISSUE TITLE
Decouple `riff doctor` command from knowledge of the cluster internals

### ISSUE THREAD

**Issue by scothis** [projectriff/cli#13]
The `riff doctor` command gives users the ability to perform basic checks on the health of the cluster and whether riff is ready for use. We should not bake intimate knowledge of the system runtime into the CLI.

For example, the command currently looks for the `knative-build` namespace. Knative Build is an implementation detail that is likely to change in the near future.

We have a few options:
1. live with the tight coupling
2. reduce the scope of `riff doctor` to only focus on user land concerns
3. create a generic configuration that lives in the cluster that the doctor command can process

**Comment by fbiville** [comment]
Do you have specific ideas with option #2?
It seems to me it's hard to diagnose if something works without looking "under the hood".

**Comment by scothis** [comment]
Done in #61
