### ISSUE TITLE
Expose --container-ref flag to riff streaming processor create command

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#132]
Processors can now resolve images via a container ref, as per [this commit](https://github.com/projectriff/system/commit/d21c78817005380f1b37d1430191dc6d6ec5823a) on riff system.
The CLI should expose the option so that end users can benefit from this.

**Comment by scothis** [comment]
Let's also expose `--image`

**Comment by fbiville** [comment]
`--container-ref` validation done during today's Paris Hackergarten vers @AElMehdi and @yeshzaoui :)

**Comment by scothis** [comment]
done in #135
