### ISSUE TITLE
CLI - system compatibility warning

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#142]
As a riff user I would like a warning when i try to use an older version of the CLI on a cluster with a newer set of riff system CRDs and controllers, especially after any additions or changes to those interfaces.

**Comment by scothis** [comment]
There's not much to do here. Once we commit to backwards compatibility for CRDs (v1beta1+) then the CLI will need to pick which version of the resource to interact with. If the cluster doesn't support that version, then the CLI request will fail.

Especially with snapshots, breakages are expected between builds. There isn't a common version we can sniff to ensure compatibility.
