### ISSUE TITLE
"riff credentials apply .. --docker-hub $ID" succeeds even when $ID is empty 

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#145]
```sh
export DOCKER_USER=

riff credentials apply docker-push \
  --docker-hub $DOCKER_USER \
  --set-default-image-prefix \
&& echo "yes that worked"
```

...enter a random password when prompted
```
Docker Hub password: 
Apply credentials "docker-push"
yes that worked
```

**Comment by scothis** [comment]
This isn't specific to DockerHub. The CLI does not validate the credentials are correct. It takes what you give it and creates the appropriate secret within the cluster.

**Comment by jldec** [comment]
I think the CLI should error on the missing argument to the --docker-hub flag since this is likely to be a problem with usage of the command, (not a case of credential validation.)

Will fle a separate issue since that applies to many flags, not just --docker-hub.
