### ISSUE TITLE
Improve parameter validation

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#151]
There are cases where flags with parameters do not result in meaningful errors e.g. when the parameters are completely missing.

E.g. In some cases the CLI will simply treat the next flag as the parameter e.g
```
$ riff container create inventory-gui2 --image --tail
Created container "inventory-gui2"
$ riff container list
NAME             LATEST IMAGE          STATUS   AGE
inventory-gui    jldec/inventory-gui   Ready    16h
inventory-gui2   --tail                Ready    55s
```

If there is concern about allowing parameter values which also happen to look exactly like supported flags, maybe that could be addressed by allowing a `--flag=--weird-value` syntax in addition to the `--flag --weird-value`.

**Comment by scothis** [comment]
I don't think we should muck with Cobra's flag parsing. It's quite good.

What we should do is add basic validation for every flag value. For example, `--tail` is not a valid image, so we can detect that and error out before creating the resource. We should also update the validation server side to reject the resource creation for the same reason.

> allowing a `--flag=--weird-value` syntax in addition to the `--flag --weird-value`

That should already work.
