### ISSUE TITLE
Change version flag to subcommand

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#161]
At the moment, one has to execute `riff --version`. `riff version` seems more idiomatic.

**Comment by scothis** [comment]
Cobra provides built-in support for `--version` to print a preset string. See

https://github.com/projectriff/cli/blob/19b45daecbd94f049426cd630b5edf6b4023ce01/pkg/riff/commands/root.go#L40-L45

Adding a version command makes sense if there is work that needs to be done to report the version (like looking up something on the server). Absent that. I'd rather keep the current behavior as is.

**Comment by jldec** [comment]
I agree with @fbiville that `riff version` feels more ideomatic across tools in the go/k8s community. Requiring users to enter `--version` when tools like kubectl use `version` can be irritating. I don't think users care whether there is work internally or not, or whether cobra has built-in support.
