### ISSUE TITLE
riff version should display system component version

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#162]
Currently, `riff --version` (or `riff version` once/if https://github.com/projectriff/cli/issues/161 is solved) only outputs the version of the CLI.

Having other components' versions would be useful for bug reports.

The exhaustive list is TBD at the moment, but it should include at least:

- invokers' versions
- system version
- kpack version

**Comment by scothis** [comment]
It would be reasonable to add this information to `riff doctor`. It's helpful to have one command to run to collect diagnostic info rather than two.
