### ISSUE TITLE
Notarize macOS binary

### ISSUE THREAD

**Issue by scothis** [projectriff/cli#195]
macOS Catalina adds a security warning for arbitrary binaries, which force the user to allow the binary to run. We can remove this friction by notarizing the binary. The process looks a bit harry, but doable from a Mac.

Currently all binaries are cross compiled in CI from a linux "stage" job. We can instead build each binary at the tail end of the "unit" job which is OS specific. Allowing macOS specific items to run.

See https://developer.apple.com/news/?id=09032019a

**Comment by jldec** [comment]
@scothis did you figure out whether or not this requires first setting up an Apple Developer Program account for our team/project?

According to https://developer.apple.com/developer-id/ 
>  Please note that you must be the Account Holder of your development team in the Apple Developer Program.
