### ISSUE TITLE
Add "riff streaming gateway list" command

### ISSUE THREAD

**Issue by trisberg** [projectriff/cli#201]
I might want to see what gateways are available without having to know what kind implementation they are or having to list each implementation separately.

Similar to list returned with `kubectl get gateway.streaming.projectriff.io`

**Comment by scothis** [comment]
the riff cli is already in dev-utils

**Comment by trisberg** [comment]
This is a suggestion for the CLI, not dev-utils

**Comment by scothis** [comment]
> This is a suggestion for the CLI, not dev-utils

E_TOO_MANY_REPOS
