### ISSUE TITLE
[testing] command_table panics with some k8s objects

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#25]
Currently, the objects are hashed as follows (see `pkg/testing/command_table.go`):
```golang
func objKey(o runtime.Object) string {
	on := o.(kmeta.Accessor)
	// namespace + name is not unique, and the tests don't populate k8s kind
	// information, so use GoLang's type name as part of the key.
	return path.Join(reflect.TypeOf(o).String(), on.GetNamespace(), on.GetName())
}
```
This is not guaranteed to work as `runtime.Object` does not implement `kmeta.Accessor` (lots of `runtime.Object` subtypes however do).
Case in point: I need to set up some `*APIResourceList` instances in `GivenObjects` but this is currently not possible as `*APIResourceList`, which is a `runtime.Object`, does not implement `kmeta.Accessor`.

**Comment by scothis** [comment]
`GivenObjects` should not contain `*List` resources, each item in the list should be added individually.
