### ISSUE TITLE
Optimize resource access checks in `riff doctor` 

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#31]
Currently, `riff` issues 1 `SelfSubjectAccessReview` per action verb per resource, which amounts to more than 50 whooping requests being sent to the cluster.

This could be replaced with a single `SelfSubjectRulesReview`.

**Comment by scothis** [comment]
@fbiville are you sure this is a good first issue? Given the complexities we hit with the doctor command so far, it seems far from ideal.

**Comment by fbiville** [comment]
The testing part may be challenging, but I'm following/helping along so hopefully, it won't be too troublesome.

**Comment by amithn** [comment]
@fbiville This is what I have found so far with SelfSubjectRulesReviews. I have a GKE cluster (with version GKE Cluster version is 1.13.7) and when I run this code 
```
review, err := c.Auth().SelfSubjectRulesReviews().Create(&authv1.SelfSubjectRulesReview{
			Spec: authv1.SelfSubjectRulesReviewSpec{
				Namespace: "default",
			},
		})
```
It returns with an error: 
```Error executing command:webhook authorizer does not support user rule resolution```

However, when I connect to a different Kubernetes cluster created with PKS (Pivotal Container Service) , the above code seems to work.

**Comment by fbiville** [comment]
@scothis does this mean `SelfSubjectRulesReview` is not always enabled by default? Shall we continue following that route if that's the case?

**Comment by scothis** [comment]
Slow and stable wins this race.
