### ISSUE TITLE
[testing] Allow creations/updates/deletions to be checked regardless of the order

### ISSUE THREAD

**Issue by fbiville** [projectriff/cli#32]
Currently, `CommandTableRecord#ExpectCreates` is checked in order. 
This makes it almost impossible to write an implementation that sends requests in parallel.

**Comment by scothis** [comment]
The benefit of ordering in the tests outweighs the benefit of parallelized commands. The cli should generally not be operating on so many resources that parallelizing requests will make a significant difference. If such a case is necessary, it can manage the fake client itself by not using CommandTable.
