### ISSUE TITLE
function create --wait can wait forever

### ISSUE THREAD

**Issue by ericbottard** [projectriff/cli#4]
Maybe related to https://github.com/projectriff/riff/issues/693

While testing the addition of the `--wait` flag, I ended up in a case where I think I would have waited forever. I think the issue is with https://github.com/projectriff/riff/blob/491d109453cb3204745b9581dcbc7c5a30999cd5/pkg/core/function.go#L252-L267 (the `default` case, which amounts to `ConditionUnknown`).

**Comment by scothis** [comment]
Resolved by https://github.com/projectriff/riff/pull/1302
