### ISSUE TITLE
expose container memory limits

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#67]
As a developer i would like to be able to control the memory limit for a container.

This is also exposed in [cloud run](https://cloud.google.com/run/docs/configuring/memory-limits)

See also projectriff/riff#1340

**Comment by jldec** [comment]
@scothis would you like to transfer https://github.com/projectriff/riff/issues/1340 as well?

**Comment by scothis** [comment]
@jldec no. The different being that memory controls are already available on the CRD, but not exposed via the CLI. Concurrency controls are not exposed via the Deployer CRD (although you can use Adapter), so it's a more cross cutting concern.
