### ISSUE TITLE
--local-path builds not available in Windows

### ISSUE THREAD

**Issue by jldec** [projectriff/cli#80]
```
PS > riff function create square `
>>   --local-path c:\Users\hello\square `
>>   --artifact square.js `
>>   --tail

Error executing command:
  invalid value: --local-path is not available on Windows: --local-path
```

**Comment by jldec** [comment]
☝️ is failing with a JavaScript function
See also https://github.com/projectriff/command-function-buildpack/issues/10

**Comment by scothis** [comment]
Since we can't do local builds safely, it's better to not do them at all. See #36 for the rational.

**Comment by scothis** [comment]
Before this issue is actionable, we need to have a better understanding of how other platforms handle unix based builds from windows source files, and the security implications of those approaches.
